### ISSUE TITLE
use Beam::Wire can generate "Number found where operator expected..." warnings

### ISSUE THREAD

**Issue by elderling** [preaction/Beam-Wire#64] opened 2017-08-15 22:59 UTC
I discovered this when my own tests started to spam "Number found where operator expected..." warnings after I introduced `Beam::Wire` into one of my modules. I am able to easily reproduce the error from the command line:

    perl -MTest::Exception -MBeam::Wire -e '1'
    Number found where operator expected at /Users/user/perl5/jt/perls/perl-5.16.3/lib/5.16.3/warnings.pm line 444, near "caller 1"
        (Do you need to predeclare caller?)

Reversing the order makes the warning go away:

    perl -MBeam::Wire -MTest::Exception -e '1'

I initially suspected that the problem was entirely the fault of  `Test::Exception` since it mucks about with Perl's `caller` but when I started to troubleshoot I discovered that the `Beam::Wire` module's own tests spam "Number found where operator expected ..." warnings:

```
17:40 $ cpanm --verbose Beam-Wire-1.021.tar.gz
cpanm (App::cpanminus) 1.7043 on perl 5.026000 built for darwin-2level
Work directory is /Users/jt/.cpanm/work/1502836878.12060
You have make /usr/bin/make
You have /usr/local/bin/wget
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
--> Working on Beam-Wire-1.021.tar.gz
Fetching file:///Users/jt/src/Beam-Wire/Beam-Wire-1.021.tar.gz ... OK
Unpacking Beam-Wire-1.021.tar.gz
x Beam-Wire-1.021/
x Beam-Wire-1.021/CHANGES
x Beam-Wire-1.021/CONTRIBUTING.md
x Beam-Wire-1.021/cpanfile
x Beam-Wire-1.021/lib/
x Beam-Wire-1.021/LICENSE
x Beam-Wire-1.021/Makefile.PL
x Beam-Wire-1.021/MANIFEST
x Beam-Wire-1.021/META.json
x Beam-Wire-1.021/META.yml
x Beam-Wire-1.021/README
x Beam-Wire-1.021/script/
x Beam-Wire-1.021/t/
x Beam-Wire-1.021/t/00-compile.t
x Beam-Wire-1.021/t/00-report-prereqs.dd
x Beam-Wire-1.021/t/00-report-prereqs.t
x Beam-Wire-1.021/t/container/
x Beam-Wire-1.021/t/dependency/
x Beam-Wire-1.021/t/deprecated/
x Beam-Wire-1.021/t/exception.t
x Beam-Wire-1.021/t/lib/
x Beam-Wire-1.021/t/method/
x Beam-Wire-1.021/t/regression/
x Beam-Wire-1.021/t/service/
x Beam-Wire-1.021/t/share/
x Beam-Wire-1.021/t/share/config/
x Beam-Wire-1.021/t/share/file.json
x Beam-Wire-1.021/t/share/file.pl
x Beam-Wire-1.021/t/share/file.yml
x Beam-Wire-1.021/t/share/inner_file.yml
x Beam-Wire-1.021/t/share/inner_inline.yml
x Beam-Wire-1.021/t/share/with_config.yml
x Beam-Wire-1.021/t/share/config/bad_char.yml
x Beam-Wire-1.021/t/share/config/config.yml
x Beam-Wire-1.021/t/service/attributes.t
x Beam-Wire-1.021/t/service/class_args.t
x Beam-Wire-1.021/t/service/config.t
x Beam-Wire-1.021/t/service/event_listener.t
x Beam-Wire-1.021/t/service/extends.t
x Beam-Wire-1.021/t/service/lifecycle.t
x Beam-Wire-1.021/t/service/method.t
x Beam-Wire-1.021/t/service/value.t
x Beam-Wire-1.021/t/service/with.t
x Beam-Wire-1.021/t/service/with_args.t
x Beam-Wire-1.021/t/regression/60_unprefixed_meta.t
x Beam-Wire-1.021/t/method/create_service.t
x Beam-Wire-1.021/t/method/is_meta.t
x Beam-Wire-1.021/t/lib/My/
x Beam-Wire-1.021/t/lib/My/ArgsListRole.pm
x Beam-Wire-1.021/t/lib/My/ArgsTest.pm
x Beam-Wire-1.021/t/lib/My/AttrRole.pm
x Beam-Wire-1.021/t/lib/My/ClassTest.pm
x Beam-Wire-1.021/t/lib/My/CloneRole.pm
x Beam-Wire-1.021/t/lib/My/Emitter.pm
x Beam-Wire-1.021/t/lib/My/Listener.pm
x Beam-Wire-1.021/t/lib/My/MethodTest.pm
x Beam-Wire-1.021/t/lib/My/RefTest.pm
x Beam-Wire-1.021/t/lib/My/Service.pm
x Beam-Wire-1.021/t/deprecated/event_listeners.t
x Beam-Wire-1.021/t/deprecated/method_call.t
x Beam-Wire-1.021/t/dependency/anonymous.t
x Beam-Wire-1.021/t/dependency/call.t
x Beam-Wire-1.021/t/dependency/config.t
x Beam-Wire-1.021/t/dependency/value.t
x Beam-Wire-1.021/t/container/config.t
x Beam-Wire-1.021/t/container/inner.t
x Beam-Wire-1.021/t/container/override.t
x Beam-Wire-1.021/script/beam-wire
x Beam-Wire-1.021/lib/Beam/
x Beam-Wire-1.021/lib/Beam/Wire/
x Beam-Wire-1.021/lib/Beam/Wire.pm
x Beam-Wire-1.021/lib/Beam/Wire/Help/
x Beam-Wire-1.021/lib/Beam/Wire/Help/Config.pod
Entering Beam-Wire-1.021
Checking configure dependencies from META.json
Checking if you have Module::Metadata 0 ... Yes (1.000033)
Checking if you have CPAN::Meta::Requirements 2.120620 ... Yes (2.140)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.24)
Running Makefile.PL
Configuring Beam-Wire-1.021 ... Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Beam::Wire
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
Checking if you have IO::Handle 0 ... Yes (1.36)
Checking if you have File::Spec 0 ... Yes (3.67)
Checking if you have Test::Deep 0 ... Yes (1.127)
Checking if you have Module::Runtime 0 ... Yes (0.015)
Checking if you have Path::Tiny 0.055 ... Yes (0.104)
Checking if you have Test::More 1.001005 ... Yes (1.302073)
Checking if you have Config::Any 0.23 ... Yes (0.32)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.24)
Checking if you have Moo 0 ... Yes (2.003002)
Checking if you have Beam::Emitter 0 ... Yes (1.007)
Checking if you have YAML 0 ... Yes (1.23)
Checking if you have Test::Differences 0.64 ... Yes (0.64)
Checking if you have Test::Lib 0 ... Yes (0.002)
Checking if you have Test::Exception 0 ... Yes (0.43)
Checking if you have Throwable 0 ... Yes (0.200013)
Checking if you have Data::DPath 0.51 ... Yes (0.56)
Checking if you have Beam::Service 0 ... Yes (0.001)
Checking if you have Types::Standard 0 ... Yes (1.002001)
Checking if you have IPC::Open3 0 ... Yes (1.20)
Building and testing Beam-Wire-1.021 ... cp lib/Beam/Wire/Help/Config.pod blib/lib/Beam/Wire/Help/Config.pod
cp lib/Beam/Wire.pm blib/lib/Beam/Wire.pm
Manifying 2 pod documents
PERL_DL_NONLAZY=1 "/Users/jt/perl5/perlbrew/perls/perl-5.26.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/container/*.t t/dependency/*.t t/deprecated/*.t t/method/*.t t/regression/*.t t/service/*.t
t/00-compile.t ..................... ok
t/00-report-prereqs.t .............. #
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module                       Want     Have
#     ------------------------ -------- --------
#     CPAN::Meta::Requirements 2.120620    2.140
#     ExtUtils::MakeMaker           any     7.24
#     Module::Metadata              any 1.000033
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.24
#
# === Test Requires ===
#
#     Module                  Want     Have
#     ------------------- -------- --------
#     ExtUtils::MakeMaker      any     7.24
#     File::Spec               any     3.67
#     IO::Handle               any     1.36
#     IPC::Open3               any     1.20
#     Test::Deep               any    1.127
#     Test::Differences       0.64     0.64
#     Test::Exception          any     0.43
#     Test::Lib                any    0.002
#     Test::More          1.001005 1.302073
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
#
# === Runtime Requires ===
#
#     Module           Want     Have
#     --------------- ----- --------
#     Beam::Emitter     any    1.007
#     Beam::Service     any    0.001
#     Config::Any      0.23     0.32
#     Data::DPath      0.51     0.56
#     Module::Runtime   any    0.015
#     Moo               any 2.003002
#     Path::Tiny      0.055    0.104
#     Throwable         any 0.200013
#     Types::Standard   any 1.002001
#     YAML              any     1.23
#
# === Runtime Recommends ===
#
#     Module Want    Have
#     ------ ---- -------
#     JSON    any missing
#
t/00-report-prereqs.t .............. ok
t/container/config.t ............... ok
t/container/inner.t ................ ok
t/container/override.t ............. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/container/override.t ............. ok
t/dependency/anonymous.t ........... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/dependency/anonymous.t ........... ok
t/dependency/call.t ................ Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/dependency/call.t ................ ok
t/dependency/config.t .............. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/dependency/config.t .............. ok
t/dependency/value.t ............... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/dependency/value.t ............... ok
t/deprecated/event_listeners.t ..... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/deprecated/event_listeners.t ..... ok
t/deprecated/method_call.t ......... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/deprecated/method_call.t ......... ok
t/exception.t ...................... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/exception.t ...................... ok
t/method/create_service.t .......... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/method/create_service.t .......... ok
t/method/is_meta.t ................. ok
t/regression/60_unprefixed_meta.t .. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/regression/60_unprefixed_meta.t .. ok
t/service/attributes.t ............. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/attributes.t ............. ok
t/service/class_args.t ............. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/class_args.t ............. ok
t/service/config.t ................. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/config.t ................. ok
t/service/event_listener.t ......... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/event_listener.t ......... ok
t/service/extends.t ................ Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/extends.t ................ ok
t/service/lifecycle.t .............. ok
t/service/method.t ................. ok
t/service/value.t .................. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/value.t .................. ok
t/service/with.t ................... Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/with.t ................... ok
t/service/with_args.t .............. Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
	(Do you need to predeclare caller?)
t/service/with_args.t .............. ok
All tests successful.
Files=25, Tests=81,  6 wallclock secs ( 0.09 usr  0.05 sys +  5.03 cusr  0.50 csys =  5.67 CPU)
Result: PASS
Manifying 2 pod documents
Appending installation info to /Users/jt/.perlbrew/libs/perl-5.26.0@beamwarn/lib/perl5/darwin-2level/perllocal.pod
OK
Successfully installed Beam-Wire-1.021
1 distribution installed
```

**Comment by preaction** [comment] 2017-08-16 06:59
The warning is not being generated by Beam::Wire. It's being generated by warnings.pm: `Number found where operator expected at /Users/jt/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"`.

Beam::Wire uses Test::Exception, so it's not surprising that the warning is appearing during its tests. It also only happens on recent Perls (yours is 5.26, I tested on 5.27.2, but 5.24.0 did not have the warning).

Without Test::Exception there is no warning, so I'm not sure what I can fix in Beam::Wire to make the warning go away.

**Comment by elderling** [comment] 2017-08-16 13:27
I should have mentioned that I originally identified the problem in Perl 5.16.3. I tested on 5.26.0 to see if a more-recent Perl than 5.16.3 also has the problem. It probably doesn't matter, but I had the same problem in 5.16.3 on both OSX and Centos 5.6. I understand your reluctance to attempt a fix/workaround. Would you be willing to update the POD to indicate that `Test::Exception` along with certain Perls emits this warning?

**Comment by elderling** [comment] 2017-08-16 14:18
This doesn't prove causation but at least one of the `Beam::Wire` dependencies also exhibits the same behavior: 

```
 perl -MTest::Exception -MData::DPath -e '1'
Number found where operator expected at /Users/jonathantaylor/perl5/perlbrew/perls/perl-5.26.0/lib/5.26.0/warnings.pm line 353, near "caller 1"
        (Do you need to predeclare caller?)
```

**Comment by preaction** [comment] 2017-08-16 19:27
> Would you be willing to update the POD to indicate that Test::Exception along with certain Perls emits this warning?

No. This is either a problem with Test::Exception, or it's a problem with warnings.pm. When that problem is fixed, then any documentation change in Beam::Wire will have to be undone, except for there will still be times when people still see it because they have the correct set of circumstances with which to reproduce it: A warnings.pm that uses `(caller 1)` (which is on line 353 of the warnings.pm that produces the problem, previous versions of warnings.pm used `(caller(1))` on that line) and a Test::Exception version that triggers the warning.

You should go to Test::Exception with this problem, but first you should reproduce it outside of any other dependencies.

I would accept a PR that removes Test::Exception and replaces it with Test::Fatal, but I will not be doing that work myself.

**Comment by elderling** [comment] 2017-08-16 20:28
Plausible. I'm more inclined to suspect `Data::DPath::Context` as it uses `Safe` and goes to extra lengths to get `warnings` to work properly in its `$COMPARTMENT`.

**Comment by preaction** [comment] 2017-08-16 20:37
So, you should probably try to reproduce this problem with the minimal amount of code and dependencies (How does Data::DPath trigger this problem? Can it be done without Data::DPath?). Whatever you can remove is someplace the problem isn't.

But it's certainly not fixable by Beam::Wire, so I'm closing this.

**Closed by preaction** 2017-08-16 20:37 UTC
